name: Deployment pesu_cie_dev

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  build:
    runs-on: self-hosted
    needs: test
    outputs:
      build_time: ${{ steps.build_tag_push_image.outputs.build_time }}
      image_tag: ${{ steps.build_tag_push_image.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image
        id: build_tag_push_image
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
          ECR_REPOSITORY: pesu_cie_dev
        run: |
          set -e

          BUILD_TIME=$(date +'%Y%m%d%H%M%S')
          IMAGE_TAG=${GITHUB_SHA}-${BUILD_TIME}

          echo "Building Docker image with tag $IMAGE_TAG"
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

          echo "build_time=${BUILD_TIME}" >> $GITHUB_OUTPUT
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

  tag:
    runs-on: self-hosted
    timeout-minutes: 30
    permissions:
      contents: write
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Validate TAG
        run: |
          if [ -z "${{ needs.build.outputs.build_time }}" ]; then
            echo "Error: TAG is empty. Exiting."
            exit 1
          fi
          echo "TAG=${{ needs.build.outputs.build_time }}"

      - name: Tag Repo
        env:
          TAG: ${{ needs.build.outputs.build_time }}
        run: |
          set -e
          COMMIT=$(git rev-parse HEAD)
          echo "Creating tag: ${TAG} for commit: ${COMMIT}"
          git config --global user.name "vijay-4gd"
          git config --global user.email "mvr@4gd.ai"
          git tag -a "${TAG}" -m "Tag source repo with date" $COMMIT
          git push origin ${TAG}

  deploy:
    runs-on: self-hosted
    needs: [build, tag]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Decode .env file and create on runner
        run: |
          echo "Decoding .env file"
          echo "${{ secrets.BASE64_ENCODED_ENV }}" | base64 -d > .env
          cat .env

      - name: Check if .env file exists
        run: |
          if [ ! -f .env ]; then
            echo "Error: .env file does not exist. Exiting."
            exit 1
          fi

      - name: Copy Env File
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_DEV }}
          username: ${{ secrets.EC2_USERNAME_DEV }}
          key: ${{ secrets.EC2_SSH_KEY_DEV }}
          source: .env
          target: .

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST_DEV }}
          username: ${{ secrets.EC2_USERNAME_DEV }}
          key: ${{ secrets.EC2_SSH_KEY_DEV }}
          script: |
            set -e

            docker login -u AWS -p $(aws ecr get-login-password --region ${{ secrets.AWS_REGION }}) ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

            docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/pesu_cie_dev:${{ needs.build.outputs.image_tag }} || exit 1

            docker stop pesu_cie_dev || true
            docker rm pesu_cie_dev || true

            docker run -d \
              --name pesu_cie_dev \
              --env-file .env \
              -p 3000:3000 \
              -v /opt/cie-dev-website/ssh-keys/atower:/root/.ssh/id_rsa:ro \
              -e SSH_KEY_PATH=/root/.ssh/id_rsa \
              -e GIT_SSH_COMMAND="ssh -i /root/.ssh/id_rsa -o StrictHostKeyChecking=no" \
              -e REMOTE_HOST=forgood@1.6.83.12 \
              ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/pesu_cie_dev:${{ needs.build.outputs.image_tag }}
